uid = nobody
gid = nogroup
use chroot = yes
read only = yes
list = yes
port = 1873
address = 192.168.173.128
log file = /var/log/cits3006-net02-rsync.log

[legacy-sync]
    path = /opt/cits3006/net02/share
    comment = Legacy internal synchronisation repository
